version: '3.3'

services:
  api:
    build:
      context: ./
      dockerfile: ./nest-api/Dockerfile
    container_name: nest_api1
    ports: 
      - 3000:3000
  front:
    build:
      context: ./
      dockerfile: ./react-frontend/Dockerfile
    container_name: react_front1
    ports: 
      - 3001:3000