apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      name: frontend
      labels:
        app.kubernetes.io/name: frontend
    spec:
      containers:
        - name: frontend
          image: test/react-frontend
          ports:
            - containerPort: 3000
